apiVersion: v1
data:
  values: |
    clusterID: <CLUSTER_ID>
    organization: <ORG>
    apps:
      gatewayApiCrds:
        enabled: true
      envoyGateway:
        enabled: true
      gatewayApiConfig:
        userConfig:
          configMap:
            values: |
              # gateways:
              #   default:
              #     subdomains:
              #       - hello
kind: ConfigMap
metadata:
  name: <CLUSTER_ID>-gateway-api-bundle-user-values
  namespace: org-<ORG>

---

apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: gateway-api-bundle
    app-operator.giantswarm.io/version: 0.0.0
    giantswarm.io/cluster: <CLUSTER_ID>
  name: <CLUSTER_ID>-gateway-api-bundle
  namespace: org-<ORG>
spec:
  catalog: giantswarm
  kubeConfig:
    inCluster: true
  name: gateway-api-bundle
  namespace: org-<ORG>
  userConfig:
    configMap:
      name: <CLUSTER_ID>-gateway-api-bundle-user-values
      namespace: org-<ORG>
  version: 1.5.0
